name: CI with Scandium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Ensure jq is installed for JSON parsing
      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run Scandium Test
        run: |
          # Make the API request and store the response
          response=$(curl -X POST -H "Content-Type: application/json" -H "x-api-token: 2DzWQDTnUypocm0tNkzHIubrJUb4ZF" \
            -d '{"project_id": "9d5e9b27-c3a6-423b-b1d4-ca9fb3cb7d3b", "suite_id": "9d6aebbb-055c-4a82-b0be-dcdf5bc7c32c", "browser": "chrome", "screenshot": true, "strategy": "await", "variables": {}, "retry": 0}' \
            "https://scr.getscandium.com/suites/execute")

          # Print the raw response for debugging
          echo "Raw response: $response"

          # Check if the response is in JSON format using jq's error handling
          if echo "$response" | jq . > /dev/null 2>&1; then
            # Parse status and message if JSON is valid
            status=$(echo "$response" | jq -r .data.result.status)
            message=$(echo "$response" | jq -r .message)

            # Process the test results
            if [ "$status" = "success" ]; then
              echo "Test ran successfully. Status: $status"
            else
              echo "Test ran with failure. Status: $status. Message: $message"
              exit 1
            fi
          else
            # Handle invalid JSON response
            echo "Error: The response is not valid JSON. Full response:"
            echo "$response"
            exit 1
          fi
        env:
          CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
